DefaultContentLanguage = "jp"

[languages]
  [languages.jp]
    baseURL = "https://www.ikezawa.com/jp/"
    languageCode = "jp"
    title = "ikezawa.com"
    weight = 1

  [languages.en]
    baseURL = "https://www.ikezawa.com/en/"
    languageCode = "en"
    title = "ikezawa.com"
    weight = 2


[[menu.main]]
	name = "Office-IT"
	url = "/it_general/"
    weight = 1

[[menu.main]]
    name = "IT-Infra"
    url = "/it_infra/"
    weight = 2

[[menu.main]]
    name = "Data Center"
    url = "/datacenter/"
    weight = 3


[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4